export const FETCH_GEOGRAPHY_DATA = 'FETCH_GEOGRAPHY_DATA';
export const RECEIVE_GEOGRAPHY_DATA = 'RECEIVE_GEOGRAPHY_DATA';
export const FETCH_SUBGEOGRAPHY_DATA = 'FETCH_SUBGEOGRAPHY_DATA';
export const RECEIVE_SUBGEOGRAPHY_DATA = 'RECEIVE_SUBGEOGRAPHY_DATA';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const SEARCH_PLACEHOLDER = 'Search populations by region, country, input zone';
