export const FETCH_GEOGRAPHY_DATA = 'FETCH_GEOGRAPHY_DATA';
export const RECEIVE_GEOGRAPHY_DATA = 'RECEIVE_GEOGRAPHY_DATA';
export const FETCH_SUBGEOGRAPHY_DATA = 'FETCH_SUBGEOGRAPHY_DATA';
export const RECEIVE_GEOGRAPHY_ERROR = 'RECEIVE_GEOGRAPHY_ERROR';
export const RECEIVE_SUBGEOGRAPHY_DATA = 'RECEIVE_SUBGEOGRAPHY_DATA';
export const FETCH_ADJACENT_DATA = 'FETCH_ADJACENT_DATA';
export const RECEIVE_ADJACENT_DATA = 'RECEIVE_ADJACENT_DATA';
export const RECEIVE_BOUNDS = 'RECEIVE_BOUNDS';
export const FETCH_BORDER = 'FETCH_BORDER';
export const RECEIVE_BORDER = 'RECEIVE_BORDER';
export const SELECT_STRATUM = 'SELECT_STRATUM';
export const FETCH_STRATUM_TREE = 'FETCH_STRATUM_TREE';
export const RECEIVE_STRATUM_TREE = 'RECEIVE_STRATUM_TREE';

export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR';
export const CONTRACT_SIDEBAR = 'CONTRACT_SIDEBAR';
export const SET_SIDEBAR = 'SET_SIDEBAR';

export const CHANGE_MAP = 'CHANGE_MAP';
