export const FETCH_GEOGRAPHY_DATA = 'FETCH_GEOGRAPHY_DATA';
export const RECEIVE_GEOGRAPHY_DATA = 'RECEIVE_GEOGRAPHY_DATA';
export const FETCH_SUBGEOGRAPHY_DATA = 'FETCH_SUBGEOGRAPHY_DATA';
export const RECEIVE_GEOGRAPHY_ERROR = 'RECEIVE_GEOGRAPHY_ERROR';
export const RECEIVE_SUBGEOGRAPHY_DATA = 'RECEIVE_SUBGEOGRAPHY_DATA';
export const RECEIVE_BOUNDS = 'RECEIVE_BOUNDS';

export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR';
export const CONTRACT_SIDEBAR = 'CONTRACT_SIDEBAR';

export const CHANGE_MAP = 'CHANGE_MAP';
